---
- name: "launching ec2-instances"
  ec2_instance:
        region: "{{ reg }}"
        image_id: "{{ img_id }}"
        instance_type: "{{ i_type }}"
        vpc_subnet_id: "{{ vpcsi }}"
        key_name: "{{ key }}"
        security_group: "{{ sg_group }}"
        name: "{{ item.ins_name }}"
        state: present
        aws_access_key: "{{ aws_ak }}"
        aws_secret_key: "{{ aws_sk }}"
        volumes:
        - device_name: "/dev/xvda"
          ebs:
            volume_size: "{{ vol_size }}"
            delete_on_termination: true

  register: details
      
- name: "saving the ip in inventory"
  lineinfile:
        path: "/inven.txt"
        line: "[{{ item.ins_name }}]\n{{ details.instances[0].public_ip_address }}"

- name: "saving the ip in variables file"
  lineinfile:
        path: "/ansible-scripts/details.yml"
        line: '{{ item.ins_name }}ip: "{{ details.instances[0].public_ip_address }}"'
