- hosts: localhost
  vars:
  -    ap: sudo /usr/local/bin/ansible-playbook

  tasks:
  - name: "provisioning ec2-instance for load balancer"
    shell:
       cmd: "{{ ap }}  /ansible-scripts/launch_LB.yml"

  - name: "configuring load balancer"
    shell:
       cmd: "{{ ap }}  /ansible-scripts/install_HAproxy.yml"

  - name: "provisioning ec2-instance for backend-servers"
    shell:
       cmd: "{{ ap }}  /ansible-scripts/launch_backends.yml"

  - name: "configuring backend-servers"
    shell:
       cmd: "{{ ap }}  /ansible-scripts/configure_backend.yml"
 
  - name: "starting haproxy service..."
    shell:
       cmd: "{{ ap }}  /ansible-scripts/start_LB.yml"






